import React, { FC } from 'react';
import { Card, CardContent, Chip, Divider, IconButton, Typography } from "@material-ui/core";
import { FaGithub } from 'react-icons/fa';
import { GrDeploy } from 'react-icons/gr';
import { animated, useSpring } from 'react-spring';

const Wrapper: FC = ({ children }) => {
  const animatedStyle = useSpring({
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    height: "100%",
    opacity: "1",
    from: { opacity: "0" },
  });

  return (
    <animated.div style={animatedStyle}>
      {children}
    </animated.div>
  );
}

const DockerPractice: FC = () => {
  return (
    <Card
      style={{
        display: "flex",
        flexDirection: "row",
        backgroundColor: "transparent",
        borderRadius: "2rem",
        minHeight: "100%"
      }}
    >
      <CardContent>
        <Typography variant="h6">
          docker_practice/go_01
        </Typography>
        <Typography color="textSecondary">
          <span>CRUD API Server generated by echo framework.<br/></span>
          <span>Use gorm for ORM & bootable with docker.<br/></span>
        </Typography>
        <Divider/>
        <div style={{ padding: 5 }}>
          <Chip
            style={{ margin: 1 }}
            label="Go"
            color="primary"
            variant="outlined"
          />
          <Chip
            style={{ margin: 1 }}
            label="Echo"
            color="secondary"
            variant="outlined"
          />
          <Chip
            style={{ margin: 1 }}
            label="Gorm"
            color="secondary"
            variant="outlined"
          />
          <Chip
            style={{ margin: 1 }}
            label="Docker"
            color="primary"
            variant="outlined"
          />
        </div>
        <Divider/>
        <div style={{ padding: 5 }}>
          <IconButton
            style={{ margin: 1 }}
            href="https://github.com/linnefromice/docker_practice/tree/master/go_01"
          >
            <FaGithub/>
          </IconButton>
        </div>
      </CardContent>
    </Card>
  );
}

const CreditCardForm: FC = () => {
  return (
    <Card
      style={{
        display: "flex",
        flexDirection: "row",
        backgroundColor: "transparent",
        borderRadius: "2rem",
        minHeight: "100%"
      }}
    >
      <CardContent>
        <Typography variant="h6">
          credit_card_form
        </Typography>
        <Typography color="textSecondary">
          <span>Credit card form using Nextjs.<br/></span>
          <span>Idea from medium &apos;Here Are 6 Front-End Challenges to Code&apos;.<br/></span>
        </Typography>
        <Divider/>
        <div style={{ padding: 5 }}>
          <Chip
            style={{ margin: 1 }}
            label="Next.js"
            color="secondary"
            variant="outlined"
          />
          <Chip
            style={{ margin: 1 }}
            label="css modules"
            color="secondary"
            variant="outlined"
          />
          <Chip
            style={{ margin: 1 }}
            label="sass"
            color="secondary"
            variant="outlined"
          />
        </div>
        <Divider/>
        <div style={{ padding: 5 }}>
          <IconButton
            style={{ margin: 1 }}
            href="https://github.com/linnefromice/credit_card_form_nextjs_01"
          >
            <FaGithub/>
          </IconButton>
          <IconButton
            style={{ margin: 1 }}
            href="https://linnefromice.github.io/credit_card_form_nextjs_01/"
          >
            <GrDeploy/>
          </IconButton>
        </div>
      </CardContent>
    </Card>
  );
}

const InfoOtherProducts: FC = () => {
  return (
    <Wrapper>
      <DockerPractice/>
      <CreditCardForm/>
    </Wrapper>
  );
}

export default InfoOtherProducts;
